[project]
name = "latentsense-sdk"
version = "1.0.9"
description = "The Python SDK for LatentSense Inc services. www.latentsense.com"
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydantic >= 2.10.13, < 3",
    "requests >= 2.27.1, < 3",
    "zstandard >= 0.25.0, < 1",
    "dotenv >= 0.9.0, < 1",
]

authors = [
    { name = "Toren Darby", email = "toren.darby@latentsense.ai" },
]
homepage = "https://www.latentsense.com"
repository = "https://github.com/latentsense/python-sdk"
documentation = "https://docs.latentsense.com"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"